[package]
name = "godot_rs_keepass"
version = "0.1.1"
authors = ["Guillaume Turchini <orion+github@orion78.fr>"]
edition = "2018"

[dependencies]
gdnative = "0.9.3"
keepass = "0.4.9"
otpauth-uri = "1.0.3"
base64 = "0.13"

[target.'cfg(target_os = "android")'.dependencies]
jni-android-sys = { version = "0.0.10", features = ["api-level-28", "android-content-Intent", "java-lang-String"] }
jni-glue        = { version = "0.0.10", features = ["unsafe-manual-jni-load-unload"] }
jni-sys         = "0.3"
lazy_static     = "1.4.0"

# Dependencies for tests
[dev-dependencies]

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = true
opt-level = 3
lto = true

# Try to patch the chrono compile bug for wasm target
[patch.crates-io]
chrono = { git = 'https://github.com/orion78fr/chrono', branch = "main" }
otpauth-uri = { git = 'https://github.com/orion78fr/otpauth-uri', branch = "master" }
keepass = { git = 'https://github.com/orion78fr/keepass-rs', branch = "master" }
gdnative-sys = { path = "../../../godot-rust/gdnative-sys" }