[package]
name = "godot_rs_keepass"
version = "0.1.1"
authors = ["Guillaume Turchini <orion+github@orion78.fr>"]
edition = "2018"

[dependencies]
gdnative = "0.9.3"
keepass = "0.4.9"
otpauth-uri = "1.0.3"
base64 = "0.13"
crypto-mac = "0.6.2"

# Dependencies for tests
[dev-dependencies]

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = true
opt-level = 3
lto = true

[patch.crates-io]
chrono = { git = 'https://github.com/chronotope/chrono', rev = "f6bd567bb677262645c1fc3131c8c1071cd77ec3" }
otpauth-uri = { git = 'https://github.com/orion78fr/otpauth-uri', branch = "master" }
keepass = { git = 'https://github.com/orion78fr/keepass-rs', branch = "master" }
gdnative = { git = "https://github.com/godot-rust/godot-rust", rev = "42a6e768a02ed32068ae1dfe5a5e655181ea2e6f" }
crypto-mac = { git = "https://github.com/RustCrypto/traits", tag = "crypto-mac-v0.6.2" } # Version is yanked
