#!/bin/bash

declare -a arr

for f in "$@"; do
    if [[ "$f" == *.rlib ]]; then
        ar --output "$(dirname "$f")" -x "$f"
        
        while read -r o; do
            fo=$(dirname "$f")/$o
            
            arr+=("$fo")
        done < <(ar -t "$f" | grep .o)
    else
        arr+=("$f")
    fi
done

declare -a arr_bis

while read -r i; do
    if [[ "${arr[$i]}" == "-l" && "${arr[$((i+1))]}" == "c" ]]; then
          while read -r j; do
          if [[ "$j" != "$i" && "$j" != "$((i+1))" ]]; then
            arr_bis+=("${arr[$j]}")
          fi
        done < <(seq 0 $((${#arr[*]}-2)))
        
        arr=("${arr_bis[@]}")
        
        break
    fi
done < <(seq 0 $((${#arr[*]}-2)))

emcc "${arr[@]}"
