name: Godot build and exports
on: [push, pull_request]

env:
  GODOT_VERSION: 3.3
  EXPORT_NAME: keepassTotp
  CARGO_TERM_COLOR: always

jobs:
  export-win:
    name: Windows export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup godot templates
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p exports/win
          godot -v --export "Windows" exports/win/${EXPORT_NAME}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows build
          path: exports/win
          retention-days: 14

  export-lin:
    name: Linux export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup godot templates
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p exports/lin
          godot -v --export "Linux" exports/lin/${EXPORT_NAME}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Linux build
          path: exports/lin
          retention-days: 14

  export-mac:
    name: MacOSX export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup godot templates
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p exports/mac
          godot -v --export "Mac" exports/mac/${EXPORT_NAME}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MacOSX build
          path: exports/mac
          retention-days: 14

  export-android:
    name: Android export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup godot templates
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Install Android build tools
        run: |
          sdkmanager "build-tools;30.0.3"
          #sdkmanager "platforms;android-30"
          
      - name: Install aarch64 android rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-linux-android
      - name: Install x86_64 android rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-linux-android 
          
      - name: Compile native lib for aarch64 android
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target aarch64-linux-android --release
      - name: Compile native lib for x86_64 android
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-linux-android --release
          
      - name: Build
        run: |
          godot -e -q
          echo 'export/android/android_sdk_path = "'${ANDROID_SDK_ROOT}'"' >> ~/.config/godot/editor_settings-3.tres
          echo 'export/android/debug_keystore = "/root/debug.keystore"' >> ~/.config/godot/editor_settings-3.tres
          echo 'export/android/debug_keystore_user = "androiddebugkey"' >> ~/.config/godot/editor_settings-3.tres
          echo 'export/android/debug_keystore_pass = "android"' >> ~/.config/godot/editor_settings-3.tres
          echo 'export/android/force_system_user = false' >> ~/.config/godot/editor_settings-3.tres
          echo 'export/android/shutdown_adb_on_exit = true' >> ~/.config/godot/editor_settings-3.tres
          mkdir -v -p exports/android
          godot -v --export-debug "Android" exports/android/${EXPORT_NAME}.apk
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Android APK
          path: exports/android
          retention-days: 14

